services:
  - type: web
    name: video-transcribe-backend
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: OPENAI_API_KEY
        sync: false

